Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,4 +1,4 @@
-name: 'github-action-docker-swarm-deploy'
+name: 'docker-swarm-deploy-github-action'
 description: 'Deploy your Docker Swarm apps in seconds. 🚀'
 inputs:
   docker_compose_file_path:
@@ -87,7 +87,7 @@ runs:
       run: |
         echo "::group::Validating SSH Connection"
         echo "Attempting to connect to one of the provided hosts: ${{ inputs.ssh_remote_hostnames }} on port ${{ inputs.ssh_remote_port }} as user ${{ inputs.ssh_deploy_user }}"
-
+        
         attempt_ssh_connection() {
           local ssh_options="$1"
           timeout 10s ssh $ssh_options -p ${{ inputs.ssh_remote_port }} ${{ inputs.ssh_deploy_user }}@$2 exit 2>/dev/null
@@ -100,37 +100,33 @@ runs:
         # Split the hosts into an array
         IFS=',' read -ra HOSTS <<< "${{ inputs.ssh_remote_hostnames }}"
 
-        # Populate known_hosts file for all provided hosts
-        if [[ -n "${{ inputs.ssh_remote_known_hosts }}" ]]; then
-          echo "${{ inputs.ssh_remote_known_hosts }}" > "$temp_known_hosts_file"
-        else
-          echo "::notice::Using ssh-keyscan to generate known_hosts entries for all provided hosts."
-          for host in "${HOSTS[@]}"; do
-            ssh-keyscan -p ${{ inputs.ssh_remote_port }} -H "$host" >> "$temp_known_hosts_file"
-          done
-        fi
-
-        # Ensure the known_hosts file is not empty
-        if [ ! -s "$temp_known_hosts_file" ]; then
-          echo "::error::The known_hosts file is empty. This indicates an issue with the provided known_hosts or ssh-keyscan process."
-          exit 1
-        fi
-
-        # Iterate over the hosts to find a successful connection
         for host in "${HOSTS[@]}"; do
           echo "Trying SSH connection to $host"
-          if attempt_ssh_connection "-o BatchMode=yes -o ConnectTimeout=5 -o UserKnownHostsFile=$temp_known_hosts_file" "$host"; then
-            echo "SSH connection successful with provided known_hosts to $host"
-            connection_successful=true
-            chosen_host="$host"
-            break
+          # If known_hosts is provided, try to use it
+          if [[ -n "${{ inputs.ssh_remote_known_hosts }}" ]]; then
+            echo "${{ inputs.ssh_remote_known_hosts }}" > "$temp_known_hosts_file"
+            if attempt_ssh_connection "-o BatchMode=yes -o ConnectTimeout=5 -o UserKnownHostsFile=$temp_known_hosts_file" "$host"; then
+              echo "SSH connection successful with provided known_hosts to $host"
+              connection_successful=true
+              chosen_host="$host"
+              break
+            else
+              echo "::warning::Failed to connect to $host with provided known_hosts. Trying without strict host key checking..."
+              if attempt_ssh_connection "-o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no" "$host"; then
+                echo "::error::Connection succeeded without strict host key checking but failed with provided known_hosts.%0A%0A\
+                Your known_hosts file is incorrect. Please test and validate your known_hosts file.%0A%0A\
+                For more information see the serversideup/github-action-docker-swarm-deploy README."
+                exit 1
+              fi
+            fi
+            # Clean up the temporary file
+            rm -f "$temp_known_hosts_file"
           else
-            echo "::warning::Failed to connect to $host with provided known_hosts. Trying without strict host key checking..."
             if attempt_ssh_connection "-o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no" "$host"; then
-              echo "::error::Connection succeeded without strict host key checking but failed with provided known_hosts.%0A%0A\
-              Your known_hosts file is incorrect. Please test and validate your known_hosts file.%0A%0A\
-              For more information see the serversideup/github-action-docker-swarm-deploy README."
-              exit 1
+              echo "SSH connection successful to $host"
+              connection_successful=true
+              chosen_host="$host"
+              break
             fi
           fi
         done
@@ -153,14 +149,14 @@ runs:
         7. Server SSH configuration: Verify it allows connections from GitHub Actions IP range%0A\
         8. If provided, verify ssh_remote_known_hosts is correct and up-to-date%0A%0A\
         For more information see the serversideup/github-action-docker-swarm-deploy README."
-
+        
         if [[ "$ACTIONS_STEP_DEBUG" == "true" ]]; then
           echo "::group::Detailed SSH Debug Output"
           ssh -vvv -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=5 \
             -p ${{ inputs.ssh_remote_port }} ${{ inputs.ssh_deploy_user }}@${{ inputs.ssh_remote_hostnames }} exit
           echo "::endgroup::"
         fi
-
+        
         echo "::endgroup::"
         exit 1
       shell: bash
